import type { Metadata } from "next";
import Link from "next/link";
import {
  ArrowRight,
  CircleDollarSign,
  Clock,
  Handshake,
  Wrench,
} from "lucide-react";

import Footer from "@/components/Footer";
import PageHero from "@/components/PageHero";

export const metadata: Metadata = {
  title: "Why Partner With Us",
  description:
    "Discover how AfterHours Vending helps nightlife venues add customer convenience and a potential new revenue stream.",
};

export default function WhyPartnerPage() {
  return (
    <>
      <main>
        <PageHero
          eyebrow="Why Partner With Us"
          title="Built to Be Easy for Venue Owners."
          description="AfterHours Vending is designed around a simple idea: give nightlife venues another amenity and revenue opportunity without adding another job for the staff."
          image="https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=2200&q=88"
        />

        <section className="partner-section">
          <div className="container partner-grid">
            <Reason
              icon={<Handshake />}
              title="Simple Partnership"
              text="Clear responsibilities, defined revenue terms, and a straightforward placement agreement."
            />

            <Reason
              icon={<CircleDollarSign />}
              title="Revenue Potential"
              text="The venue can participate in revenue generated by machine sales."
            />

            <Reason
              icon={<Wrench />}
              title="Managed Service"
              text="We handle stocking, servicing, monitoring, and maintenance."
            />

            <Reason
              icon={<Clock />}
              title="Customer Convenience"
              text="Guests can access products without leaving the venue."
            />
          </div>

          <div className="container partner-cta">
            <h2 className="display-font">
              Let&apos;s Talk About Your Venue.
            </h2>

            <Link
              href="/request-a-machine"
              className="primary-button"
            >
              Request a Machine
              <ArrowRight size={18} />
            </Link>
          </div>
        </section>
      </main>

      <Footer />

      <style>{`
        .partner-section {
          padding: 115px 0 125px;
          background: #090909;
        }

        .partner-grid {
          display: grid;
          grid-template-columns: repeat(2, 1fr);
          gap: 18px;
        }

        .reason {
          padding: 38px;
          border: 1px solid rgba(224, 180, 95, 0.16);
          border-radius: 12px;
          background: linear-gradient(145deg, #111, #090909);
        }

        .reason-icon {
          color: var(--gold-light);
          margin-bottom: 45px;
        }

        .reason-icon svg {
          width: 30px;
          height: 30px;
          stroke-width: 1.5;
        }

        .reason h3 {
          margin: 0 0 12px;
          font-family: var(--font-display);
          font-size: 2rem;
          font-weight: 500;
        }

        .reason p {
          color: #99958e;
          line-height: 1.75;
        }

        .partner-cta {
          margin-top: 70px;
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 40px;
          border: 1px solid rgba(224, 180, 95, 0.18);
          background: #0d0d0d;
        }

        .partner-cta h2 {
          margin: 0;
          font-size: 2.8rem;
          font-weight: 500;
        }

        @media (max-width: 700px) {
          .partner-grid {
            grid-template-columns: 1fr;
          }

          .partner-cta {
            align-items: flex-start;
            flex-direction: column;
            gap: 25px;
          }
        }
      `}</style>
    </>
  );
}

function Reason({
  icon,
  title,
  text,
}: {
  icon: React.ReactNode;
  title: string;
  text: string;
}) {
  return (
    <article className="reason">
      <div className="reason-icon">
        {icon}
      </div>

      <h3>{title}</h3>
      <p>{text}</p>
    </article>
  );
}